Check offchain data for duplicates
0xPolygon/cdk-data-availability pull request #112
Opened 2024-08-13 17:17 UTC by begmaroman

…list

2024-08-14 14:05 UTC, arnaubennassar requested changes
looks like the PR covers the case where there are duplicated inserts within the same query, but not if one of the items about to get inserted already exist on the DB

2024-08-14 14:31 UTC, begmaroman commented on db/db.go
> +	fmt.Println("ods 2", ods)
Done

2024-08-19 08:34 UTC, goran-ethernal commented
Did we agree on the detection of batch gap, because we also index with Batch Number? It will now be more and more frequent since batches can have the same `L2Data`. Do we just log the gaps, and call it a day, or do we have some logic attached after we detect a gap? I don't recall.

2024-08-19 08:40 UTC, arnaubennassar approved these changes

2024-08-19 09:06 UTC, merged